services:
  - type: web
    name: royalstone-lanka
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://vajirask249_db_user:zKKIu8O3HRSg1uU2@cluster0.nx1ewgq.mongodb.net/royalstone?retryWrites=true&w=majority&appName=Cluster0
