services:
  - type: web
    name: royalstone-lanka
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb://vajirask249_db_user:zKKIu8O3HRSg1uU2@ac-lexrp1j-shard-00-00.nx1ewgq.mongodb.net:27017,ac-lexrp1j-shard-00-01.nx1ewgq.mongodb.net:27017,ac-lexrp1j-shard-00-02.nx1ewgq.mongodb.net:27017/royalstone?ssl=true&replicaSet=atlas-g1quo5-shard-0&authSource=admin&retryWrites=true&w=majority
